# general properties

## Resources
spring.web.resources.add-mappings=false

spring.servlet.multipart.max-file-size=3MB
# spring.servlet.multipart.max-request-size=1024MB
spring.servlet.multipart.enabled=true

## Logging
spring.output.ansi.enabled=always

## App settings
restgourmet.api.jwt-cookie-name=restgourmet-jwt
restgourmet.api.jwt-refresh-cookie-name=restgourmet-refresh-jwt

## OpenAPI
openapi.service.title=restgourmet Core API
openapi.service.version=v0.1
