## development env properties
OPEN_EXCHANGE_RATES_APP_ID=""

server.port=8000

## JPA
# SQLite JDBC URL — o arquivo será criado na raiz do projeto
spring.datasource.url=jdbc:sqlite:meubanco.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Dialect do Hibernate mantido pela comunidade
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect

# Hibernate DDL auto
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL (opcional)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

## Cache
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis

## Swagger/OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.show-actuator=true
springdoc.cache.disabled=true
springdoc.swagger-ui.persist-authorization=true
springdoc.swagger-ui.doc-expansion=none
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha


## Logging
# logging.level.security.app.restgourmet.api.AuthTokenFilter=DEBUG
# logging.level.org.springframework.security=DEBUG
# logging.level.app.restgourmet=DEBUG
# logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
