## development env properties

# logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

## JPA
spring.jpa.generate-ddl=true
spring.jpa.datasource.ddl-auto=create
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.show-sql=true

springdoc.api-docs.path=/api-docs
springdoc.show-actuator=true
springdoc.cache.disabled=true
springdoc.swagger-ui.persist-authorization=true

## Security
# logging.level.security.app.restgourmet.api.AuthTokenFilter=DEBUG
# logging.level.org.springframework.security=DEBUG
