@hostname = http://localhost
@port = 8080
@host = {{hostname}}:{{port}}
@contentType = application/json


POST {{host}}/api/auth/register
Accept: */*
Content-Type: application/json

{
  "identifier": "johndoe@test.com",
  "password": "password"
}

###

POST {{host}}/api/auth/login
Accept: */*
Content-Type: {{contentType}}

{
  "identifier": "admin",
  "password": "admin"
}

###

GET {{host}}/api/users/a558b8ed-93e1-4019-9166-40f2684d46f6
Accept: */*
Content-Type: application/json
Cookie: restgourmet-jwt=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzcHJpbmctc2VjdXJpdHktand0Iiwic3ViIjoiYWRtaW4iLCJleHAiOjE3NDE3NzkwOTIsImlhdCI6MTc0MTc0MzA5Mn0.SGcfQLMxXx19-6fVLzzy3JNlmIKOwLs386nFK3QZsgM

